### ISSUE TITLE
Problem with Transient_..._right and Transient_..._left

### ISSUE THREAD

**Issue by FrancoisGLEYZON** [blackpressinc/1D_Transient_Toolbox#1]
Hello Sir,
sorry to disturbing you. First and foremost, thank you for your simulation code, it's an amazing work ! 
However, I am currently facing an issue with it because, there is a part in the code where the simulation say it can't find the variables of the form : Transient_..._right and Transient_..._left. After re-rend all your comments and trying to understand how it works, I think the problem may come from the lines 129 and 172 (with the update document) where you define the function global. As you said in comments, these move doesn't seem to work all the time. As regards, do you have an idea how I can overcome this difficulty ? Whereas you, I am not an expert in Python, so  I do not have so many ideas on how to do it, unfortunately ...
Thank you again for your work, it's incredible ! 
Wishing you a nice day, 
Best regards, 
François
![Capture](https://user-images.githubusercontent.com/95983493/145774812-5b2fe93c-65bf-4c2a-b63e-35d91aa2eef9.PNG)

 PS : It may also come from the fact that the code may not find the different xlsx document. It doesn't say there is an error, but maybe he is not able to find the documents. Do you think the issue come from that too ?

**Comment by blackpressinc** [comment]
> 
Francois! 

Sorry for the late reply. Thank you for your feedback! That error does come from the globals() and those variables should become defined at run time if any of the Transient boolean conditions are turned on _and_ if a valid .xlsx is available for that boundary. As a temporary fix you can create those variable names manually. I have updated the code with those variable names commented out where they would normally be imported. In the future I hope to handle this a lot better.

I am currently adding all the necessary code for tracking uncertainty statistics for any analysis. If you find any other bugs or have any requests please let me know. The changes should be pushed up in a few minutes. This is my first GitHub project so there are growing pains.
